project:
  type: website
  output-dir: docs

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Brittany's Blog"
  navbar:
    right:
      - about.qmd
      - contact.qmd 
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://twitter.com
format:
  html:
    theme:
      - solar
      - brand
    css: styles.css



